export default {
    user: {
        token: sessionStorage.getItem("TOKEN"),
        data: {},
    },
    products: {
        loading: false,
        links: [],
        from: null,
        to: null,
        page: 1,
        limit: null,
        total: null,
    },
    orders: {
        loading: false,
        data: [],
        links: [],
        from: null,
        to: null,
        page: 1,
        limit: null,
        total: null,
    },
    dateOptions: [
        {key: '1 day', text: 'Yesterday'},
        {key: '1 week', text: 'Last Week'},
        {key: '2 weeks', text: 'Last 2 Weeks'},
        {key: '1 month', text: 'Last Month'},
        {key: '3 months', text: 'Last 3 Months'},
        {key: '6 months', text: 'Last 6 Months'},
        {key: 'all', text: 'All Time'},
    ],
    users: {
        loading: false,
        data: [],
        links: [],
        from: null,
        to: null,
        page: 1,
        limit: null,
        total: null,
    },
    customers: {
        loading: false,
        data: [],
        links: [],
        from: null,
        to: null,
        page: 1,
        limit: null,
        total: null,
    },
    countries: [],
};
